Repository rust-lang/rust-forge, pull requests merged in 2025-02, with the labels that each got.

#805 Add notes about stabilized APIs
  src/release/release-notes.md
Labels: S-waiting-on-review

#799 release: document pinging `relnotes-interest-group` for relnotes PRs and relnotes blog posts
  src/release/release-notes.md
Labels: S-waiting-on-review, T-release

#807 Add link to State of Rust FAQ to the surveys repo
  src/community/README.md
  src/community/survey-faq.md
Labels: S-waiting-on-review

#810 make link clickable
  src/release/release-notes.md
Labels: S-waiting-on-review

#811 most important criter{ia => ion}
  src/compiler/membership.md
Labels: S-waiting-on-review

#808 document additional labels
  src/release/issue-triaging.md
Labels: S-waiting-on-review

#812 Remove "Survey FAQ" deadlink from SUMMARY
  src/SUMMARY.md
Labels: S-waiting-on-review

#804 rewrite compiler team documentation
  book.toml
  src/SUMMARY.md
  src/compiler/README.md
  src/compiler/calendar.md
  src/compiler/cross-compilation/README.md
  src/compiler/cross-compilation/windows.md
  src/compiler/mcp.md
  src/compiler/meetings.md
  src/compiler/membership.md
  src/compiler/new_option.md
  src/compiler/notification-groups.md
  src/compiler/prioritization.md
  src/compiler/prioritization/priority-levels.md
  src/compiler/prioritization/procedure.md
  src/compiler/proposals-and-stabilization.md
  src/compiler/resources.md
  src/compiler/reviews.md
  src/compiler/steering-meeting.md
  src/compiler/steering-meeting/how-to-run-design.md
  src/compiler/steering-meeting/how-to-run-planning.md
  src/compiler/steering-meeting/submit.md
  src/compiler/third-party-out-of-tree.md
  src/compiler/triage-meeting.md
Labels: S-waiting-on-review, T-compiler, S-waiting-on-team
