Repository rust-lang/rust-forge, pull requests merged in 2025-01, with the labels that each got.

#794 Update issue triaging docs
  src/release/issue-triaging.md
Labels: S-waiting-on-review, T-compiler, T-release

#792 bors: document how to properly resync bors queue
  src/SUMMARY.md
  src/infra/docs/bors.md
  src/infra/docs/bors/queue-resync.md
Labels: S-waiting-on-review, T-infra

#801 Automatically add rendered link to pull-requests
  triagebot.toml
Labels: S-waiting-on-review

#800 Update release note process for current tooling
  src/release/release-notes.md
Labels: S-waiting-on-review

#802 Update compiler team membership page
  src/compiler/mcp.md
  src/compiler/membership.md
Labels: S-waiting-on-review
