Repository rust-lang/rust-forge, pull requests merged in 2025-03, with the labels that each got.

#814 Move to the forge remaining T-compiler docs
  src/SUMMARY.md
  src/compiler/README.md
  src/compiler/meetings.md
  src/compiler/operations.md
  src/compiler/prioritization.md
Labels: S-waiting-on-review

#815 Mention `r? compiler_leads` in adding a new target process
  src/compiler/proposals-and-stabilization.md
Labels: S-waiting-on-review

#816 Document triagebot period-in-label caveat
  src/release/issue-triaging.md
Labels: S-waiting-on-review

#818 Add procedure when "Extending the behavior of a stable flag"
  src/compiler/proposals-and-stabilization.md
Labels: S-waiting-on-review

#819 Remove mention of IP allowlist for bastion
  src/infra/docs/bastion.md
Labels: S-waiting-on-review

#817 Migrate Compiler docs about WGs
  src/SUMMARY.md
  src/compiler/README.md
  src/compiler/working-areas.md
Labels: S-blocked

#803 link to stabilization docs in the rustc-dev-guide
  src/SUMMARY.md
  src/lang/stabilization-procedure.md
Labels: S-waiting-on-review, T-lang

#820 Update T-compiler zulip channels' names
  src/compiler/notification-groups.md
  src/compiler/prioritization.md
  src/compiler/working-areas.md
  src/platforms/zulip.md
  src/triagebot/zulip-notifications.md
Labels: S-waiting-on-review
