Repository rust-lang/rust-forge, pull requests merged in 2025-05, with the labels that each got.

#843 add "Team Roles" section to "Issue Triage" page
  src/release/issue-triaging.md
Labels: S-waiting-on-author

#840 docs(policy): Clarify that Expatriation applies to all categories
  src/policies/crate-ownership.md
Labels: S-waiting-on-review

#845 Update Blog policy
  src/platforms/blogs.md
Labels: S-waiting-on-review

#847 updated docs regarding dev desktop: github account id is case sensitive
  src/infra/docs/dev-desktop.md
Labels: S-waiting-on-review

#838 Add T-compiler ops work description
  src/compiler/operations.md
Labels: S-waiting-on-review

#849 Add documentation about quoted labels
  src/triagebot/labeling.md
Labels: S-waiting-on-review

#850 Mention `check-commits = false` for triagebot `[issue-links]`
  src/triagebot/issue-links.md
Labels: S-waiting-on-review

#854 Fix a few links
  src/compiler/operations.md
  src/compiler/proposals-and-stabilization/ecosystem-integration-tests.md
Labels: S-waiting-on-review

#860 add skeleton for how to join a team; suggest joining wg-triage
  src/onboarding.md
Labels: S-waiting-on-review

#864 fix typo in compiler membership documentation
  src/compiler/membership.md
Labels: S-waiting-on-review

#866 Deduplicate rustup's other installation methods docs by delegating to rustup docs
  blacksmith/src/lib.rs
  src/infra/other-installation-methods.md
Labels: S-waiting-on-review

#862 Update mdbook dependency
  .github/workflows/deploy.yml
  blacksmith/Cargo.lock
  blacksmith/Cargo.toml
Labels: S-waiting-on-review

#867 Add documentation for triagebot `concern` command
  src/SUMMARY.md
  src/triagebot/concern.md
Labels: S-waiting-on-review

#848 Document compiler backport nomination/review process
  src/SUMMARY.md
  src/compiler/README.md
  src/compiler/backports.md
  src/compiler/proposals-and-stabilization.md
Labels: S-waiting-on-review, T-compiler

#853 Document triagebot review queue tracking
  src/SUMMARY.md
  src/triagebot/pr-assignment-tracking.md
  src/triagebot/pr-assignment.md
  src/triagebot/review-queue-tracking.md
Labels: S-waiting-on-review
